#!/usr/bin/env python3
"""Builds preview.html from preview_template.html by inlining every asset
as a base64 data: URI (PNGs, SVG, and the true per-size entries inside
logo.ico). Rerun after `generate.py` whenever the icons change."""

import base64
import re
import struct
from pathlib import Path

ROOT = Path(__file__).parent
LAUNCHERS = ROOT / "launchers"


def png_durl(path: Path) -> str:
    return "data:image/png;base64," + base64.b64encode(path.read_bytes()).decode()


def svg_durl(path: Path) -> str:
    return "data:image/svg+xml;base64," + base64.b64encode(path.read_bytes()).decode()


def kb(path: Path) -> str:
    return f"{path.stat().st_size / 1024:.1f} KB"


def ico_entries(path: Path) -> dict[int, str]:
    """logo.ico is PNG-embedded: each directory entry's payload is a PNG."""
    data = path.read_bytes()
    count = struct.unpack("<H", data[4:6])[0]
    out = {}
    for i in range(count):
        off = 6 + 16 * i
        size_px = data[off] or 256
        blob_len = struct.unpack("<I", data[off + 8:off + 12])[0]
        blob_off = struct.unpack("<I", data[off + 12:off + 16])[0]
        png = data[blob_off:blob_off + blob_len]
        out[size_px] = "data:image/png;base64," + base64.b64encode(png).decode()
    return out


def main() -> None:
    ico = ico_entries(ROOT / "logo.ico")
    assert set(ico) == {16, 32, 48, 64, 128, 256}, sorted(ico)

    tokens = {
        "SVG": svg_durl(ROOT / "logo.svg"),
        "LOGO512": png_durl(ROOT / "logo-512.png"),
        "LOGO256": png_durl(ROOT / "logo-256.png"),
        "LOGO32B": png_durl(ROOT / "logo-32-black.png"),
        "LOGO32W": png_durl(ROOT / "logo-32-white.png"),
        "LOGO512W": png_durl(ROOT / "logo-512-white.png"),
        "ALT_TEAL": png_durl(ROOT / "alt" / "logo-512-teal.png"),
        "ALT_BLACK": png_durl(ROOT / "alt" / "logo-512-black.png"),
        "LS512": png_durl(ROOT.parents[1] / "app" / "assets" / "img" / "logo-512.png"),
        "ICO16": ico[16],
        "ICO32": ico[32],
        "ICO48": ico[48],
        "ICO64": ico[64],
        "ICO128": ico[128],
        "ICO256": ico[256],
        # platform launchers (generated by make_launchers.py)
        "LA_LEGACY": png_durl(LAUNCHERS / "android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png"),
        "LA_FG": png_durl(LAUNCHERS / "android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png"),
        "LA_MONO": png_durl(LAUNCHERS / "android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_monochrome.png"),
        "LA_IOS": png_durl(LAUNCHERS / "ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024.png"),
        "LA_MAC": png_durl(LAUNCHERS / "macos/Runner/Assets.xcassets/AppIcon.appiconset/logo-1024-mac-512.png"),
        "LA_MASK": png_durl(LAUNCHERS / "web/icons/Icon-maskable-512.png"),
    }

    manifest = [
        ("logo.svg", ROOT / "logo.svg", tokens["SVG"], "矢量源文件 —— 平台启动图标（mipmap / AppIcon / icns）从这里派生"),
        ("logo-512.png", ROOT / "logo-512.png", tokens["LOGO512"], "应用内「关于」页 Logo（LocalSendLogo 以主题色 BlendMode.srcATop 着色）"),
        ("logo-256.png", ROOT / "logo-256.png", tokens["LOGO256"], "应用商店 / 打包"),
        ("logo-128.png", ROOT / "logo-128.png", tokens["LOGO512"], "应用内小图 / 文档"),
        ("logo-32.png", ROOT / "logo-32.png", tokens["LOGO32B"], "小尺寸 UI 引用"),
        ("logo-32-black.png", ROOT / "logo-32-black.png", tokens["LOGO32B"], "浅色托盘图标（macOS / Windows）"),
        ("logo-32-white.png", ROOT / "logo-32-white.png", tokens["LOGO32W"], "深色托盘图标"),
        ("logo-512-white.png", ROOT / "logo-512-white.png", tokens["LOGO512W"], "深色表面 / 品牌蓝底"),
        ("logo.ico", ROOT / "logo.ico", tokens["LOGO256"], "Windows 应用图标（16–256，PNG 内嵌）"),
        ("alt/logo-512-teal.png", ROOT / "alt" / "logo-512-teal.png", tokens["ALT_TEAL"], "备选配色：LocalSend 家族青"),
        ("alt/logo-512-black.png", ROOT / "alt" / "logo-512-black.png", tokens["ALT_BLACK"], "备选配色：墨黑"),
    ]
    rows = []
    for name, path, thumb, usage in manifest:
        rows.append(
            f"          <tr><td class=\"fname\">{name}</td>"
            f"<td class=\"fsize\">{kb(path)}</td>"
            f"<td class=\"fuse\">{usage}</td>"
            f"<td class=\"fthumb\"><img src=\"{thumb}\" alt=\"{name} 缩略图\"></td></tr>"
        )
    tokens["MANIFEST"] = "\n".join(rows)

    html = (ROOT / "preview_template.html").read_text()
    for key, value in tokens.items():
        html = html.replace(f"@@{key}@@", value)
    leftover = re.findall(r"@@[A-Z0-9_]+@@", html)
    assert not leftover, f"unsubstituted tokens: {leftover}"

    out = ROOT / "preview.html"
    out.write_text(html)
    print(f"done -> {out} ({out.stat().st_size / 1024:.0f} KB)")


if __name__ == "__main__":
    main()
