// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:localsend_isolates/rust/api/cancel.dart';
import 'package:localsend_isolates/rust/api/model.dart';
import 'package:localsend_isolates/rust/api/stream.dart';
import 'package:localsend_isolates/rust/frb_generated.dart';

part 'http.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `resolve_file_content`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `from`

/// Creates an HTTP client.
///
/// `expected_fingerprint` pins the peer to the certificate with that SHA-256
/// fingerprint (uppercase hex). It is enforced during the TLS handshake, so a
/// peer that does not present the expected certificate never receives the
/// request. Pass `None` only for discovery, where the peer is not known yet.
RsHttpClient createClient({
  required String privateKey,
  required String cert,
  required LsHttpClientVersion version,
  String? expectedFingerprint,
  int? timeoutMs,
}) => RustLib.instance.api.crateApiHttpCreateClient(
  privateKey: privateKey,
  cert: cert,
  version: version,
  expectedFingerprint: expectedFingerprint,
  timeoutMs: timeoutMs,
);

/// Creates a plain HTTP client without any TLS or client certificate.
///
/// Used for `fs/roots` and `fs/list` which are served on the same port as
/// the HTTPS server but accept plain HTTP. The client does not send a
/// certificate and does not verify the server certificate.
RsHttpClient createHttpOnlyClient() => RustLib.instance.api.crateApiHttpCreateHttpOnlyClient();

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<RsHttpClient>>
abstract class RsHttpClient implements RustOpaqueInterface {
  Future<void> cancel({required ProtocolType protocol, required String ip, required int port, required String sessionId});

  /// `GET /api/localsend/v2/fs/download?path=...` — stream a single
  /// file from a whitelisted root. Emits [RsFsDownloadEvent]s on [sink]:
  ///
  ///   * `Started { total_size, status }` — once, when headers arrive.
  ///     `status` is `200` for a whole-file fetch, `206` for a Range.
  ///   * `Chunk { bytes }`                — many times, body chunks.
  ///   * `Finished`                       — once, on successful EOF.
  ///   * `Failed { error }`               — once, on any error.
  ///
  /// The sink pattern mirrors [Self::upload]; flutter_rust_bridge
  /// discards the returned `Result` of functions taking a [StreamSink],
  /// so errors are emitted as a `Failed` event rather than returned
  /// (otherwise an uncaught async error would kill the calling isolate).
  ///
  /// `range_start` / `range_end`: when both are `Some`, sends
  /// `Range: bytes=start-end`. When only `start` is `Some`, sends
  /// `Range: bytes=start-` (open-ended). When both are `None`, fetches
  /// the whole file with no Range header.
  Stream<RsFsDownloadEvent> fsDownload({
    required ProtocolType protocol,
    required String ip,
    required int port,
    required String path,
    BigInt? rangeStart,
    BigInt? rangeEnd,
    required RsCancellationToken cancelToken,
  });

  /// `GET /api/localsend/v2/fs/list` — paginated directory listing under
  /// a whitelisted root. `path` is relative to the mount-point root and
  /// uses `/` as the separator; pass `""` to list the root contents.
  /// `sort` is one of `name_asc` / `name_desc` / `size_asc` / `size_desc` /
  /// `mtime_desc` (default `name_asc`).
  Future<ListResponse> listDir({
    required ProtocolType protocol,
    required String ip,
    required int port,
    required String path,
    required int page,
    required int size,
    required String sort,
  });

  /// `GET /api/localsend/v2/fs/roots` — fetch the peer's whitelisted
  /// mount points. Used by the remote file browser (T-008).
  Future<RootsResponse> listRoots({required ProtocolType protocol, required String ip, required int port});

  Future<PrepareUploadResult> prepareUpload({
    required ProtocolType protocol,
    required String ip,
    required int port,
    required PrepareUploadRequestDto payload,
    String? publicKey,
    String? pin,
    required RsCancellationToken cancelToken,
  });

  Future<ResultWithPublicKeyRegisterResponseDto> register({
    required ProtocolType protocol,
    required String ip,
    required int port,
    required RegisterDto payload,
  });

  /// Uploads a single file, emitting [RsUploadEvent]s on [sink].
  ///
  /// Failures are emitted as [RsUploadEvent::Failed] instead of being
  /// returned: flutter_rust_bridge discards the returned `Result` of
  /// functions taking a [StreamSink], so a returned error would become an
  /// uncaught async error killing the calling isolate.
  Stream<RsUploadEvent> upload({
    required ProtocolType protocol,
    required String ip,
    required int port,
    String? publicKey,
    required String sessionId,
    required String fileId,
    required String token,
    Dart2RustStreamReceiver? binary,
    String? path,
    int? fileDescriptor,
    required BigInt contentLength,
    required RsCancellationToken cancelToken,
  });
}

enum LsHttpClientVersion {
  v2,
  v3,
}

class PrepareUploadResult {
  final int statusCode;
  final PrepareUploadResponseDto? response;

  const PrepareUploadResult({
    required this.statusCode,
    this.response,
  });

  @override
  int get hashCode => statusCode.hashCode ^ response.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PrepareUploadResult && runtimeType == other.runtimeType && statusCode == other.statusCode && response == other.response;
}

class ResultWithPublicKeyRegisterResponseDto {
  final String? publicKey;
  final RegisterResponseDto body;

  const ResultWithPublicKeyRegisterResponseDto({
    this.publicKey,
    required this.body,
  });

  @override
  int get hashCode => publicKey.hashCode ^ body.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ResultWithPublicKeyRegisterResponseDto && runtimeType == other.runtimeType && publicKey == other.publicKey && body == other.body;
}

@freezed
sealed class RsFsDownloadEvent with _$RsFsDownloadEvent {
  const RsFsDownloadEvent._();

  /// Headers arrived. `total_size` is `content_length` (0 if the
  /// server did not advertise one). `status` is the HTTP status
  /// code (200 for whole-file, 206 for partial).
  const factory RsFsDownloadEvent.started({
    required BigInt totalSize,
    required int status,
  }) = RsFsDownloadEvent_Started;

  /// A chunk of body bytes. `transferred` is the cumulative byte
  /// count received so far.
  const factory RsFsDownloadEvent.chunk({
    required Uint8List bytes,
    required BigInt transferred,
  }) = RsFsDownloadEvent_Chunk;

  /// Successful end of stream.
  const factory RsFsDownloadEvent.finished() = RsFsDownloadEvent_Finished;

  /// The user cancelled the download via the cancel token.
  const factory RsFsDownloadEvent.cancelled() = RsFsDownloadEvent_Cancelled;

  /// The download failed. Always the last event of the stream.
  const factory RsFsDownloadEvent.failed({
    required RsHttpClientError error,
  }) = RsFsDownloadEvent_Failed;
}

@freezed
sealed class RsHttpClientError with _$RsHttpClientError implements FrbException {
  const RsHttpClientError._();

  const factory RsHttpClientError.statusCode({
    required int status,
    String? message,
  }) = RsHttpClientError_StatusCode;
  const factory RsHttpClientError.reqwest(
    String field0,
  ) = RsHttpClientError_Reqwest;
  const factory RsHttpClientError.json(
    String field0,
  ) = RsHttpClientError_Json;
  const factory RsHttpClientError.io(
    String field0,
  ) = RsHttpClientError_Io;
  const factory RsHttpClientError.other(
    String field0,
  ) = RsHttpClientError_Other;
}

@freezed
sealed class RsUploadEvent with _$RsUploadEvent {
  const RsUploadEvent._();

  /// The upload progress as a fraction (0.0 to 1.0). Throttled.
  const factory RsUploadEvent.progress({
    required double progress,
  }) = RsUploadEvent_Progress;

  /// The upload failed. Always the last event of the stream.
  const factory RsUploadEvent.failed({
    required RsHttpClientError error,
  }) = RsUploadEvent_Failed;
}
